"""
gen_tts.py — Generate Turkish TTS audio as C arrays for ESP32-P4 firmware.

Run this ONCE before building to create main/tts_data.h.

Requirements:
    pip install edge-tts pydub
    winget install ffmpeg   (or choco install ffmpeg)

    # OLD (still works as fallback if edge-tts unavailable):
    # pip install gtts pydub

Usage:
    cd tools
    python gen_tts.py
"""

import asyncio
import struct
import io
import os
import sys


# ── TTS engine: edge-tts (Microsoft Neural TTS) ──────────────────────
#
# Voice: tr-TR-EmelNeural  — natural female Turkish voice
# edge-tts outputs MP3; we convert to 16 kHz mono 16-bit PCM via pydub.
#
# OLD engine (gtts — Google TTS, more robotic):
# from gtts import gTTS
# tts = gTTS(text, lang=lang)
# mp3_buf = io.BytesIO()
# tts.write_to_fp(mp3_buf)
# mp3_buf.seek(0)

EDGE_TTS_VOICE = "tr-TR-EmelNeural"   # change to "tr-TR-AhmetNeural" for male voice


async def _edge_tts_to_mp3(text: str, voice: str) -> bytes:
    """Use edge-tts to generate MP3 bytes for the given text and voice."""
    try:
        import edge_tts
    except ImportError:
        print("ERROR: edge-tts not installed.  Run: pip install edge-tts")
        sys.exit(1)

    communicate = edge_tts.Communicate(text, voice)
    mp3_chunks = []
    async for chunk in communicate.stream():
        if chunk["type"] == "audio":
            mp3_chunks.append(chunk["data"])

    if not mp3_chunks:
        print(f"ERROR: edge-tts returned no audio for '{text}'")
        sys.exit(1)

    return b"".join(mp3_chunks)


def generate_mp3(text: str, voice: str) -> bytes:
    """Synchronous wrapper around the async edge-tts call."""
    # On Windows, ProactorEventLoop (default in Python 3.8+) can conflict
    # with edge-tts async networking — force SelectorEventLoop.
    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    return asyncio.run(_edge_tts_to_mp3(text, voice))


# ── OLD gtts fallback (commented out — kept for reference) ───────────
# def generate_mp3_gtts(text: str, lang: str = "tr") -> bytes:
#     from gtts import gTTS
#     buf = io.BytesIO()
#     gTTS(text, lang=lang).write_to_fp(buf)
#     buf.seek(0)
#     return buf.read()


def phrase_to_c_array(text: str, var_name: str) -> str:
    """Convert a TTS phrase to a C int16_t array definition."""
    try:
        from pydub import AudioSegment
    except ImportError:
        print("ERROR: pydub not installed.  Run: pip install pydub")
        sys.exit(1)

    print(f"  Generating TTS for: '{text}' (voice={EDGE_TTS_VOICE}) ...")

    mp3_data = generate_mp3(text, EDGE_TTS_VOICE)

    # Convert MP3 → 16 kHz mono 16-bit PCM
    try:
        audio = AudioSegment.from_mp3(io.BytesIO(mp3_data))
    except Exception as e:
        print(f"ERROR: pydub/ffmpeg failed: {e}")
        print("Make sure ffmpeg is installed and in PATH: winget install ffmpeg")
        sys.exit(1)

    audio = audio.set_frame_rate(16000).set_channels(1).set_sample_width(2)

    # Normalize to -3 dBFS — near-maximum volume without clipping
    original_dBFS = audio.dBFS
    gain_applied  = -original_dBFS - 3.0
    audio         = audio.apply_gain(gain_applied)
    print(f"    → original level: {original_dBFS:.1f} dBFS  "
          f"gain applied: {gain_applied:+.1f} dB  "
          f"final: {audio.dBFS:.1f} dBFS")

    raw    = audio.raw_data
    count  = len(raw) // 2
    samples = struct.unpack(f"<{count}h", raw)

    duration_ms = int(count / 16000 * 1000)
    print(f"    → {count} samples ({duration_ms} ms)")

    lines = []
    lines.append(f"/* '{text}'")
    lines.append(f" * Voice: {EDGE_TTS_VOICE}")
    lines.append(f" * {count} samples @ 16 kHz mono 16-bit PCM ({duration_ms} ms)")
    lines.append(f" * Generated by tools/gen_tts.py — do not hand-edit")
    lines.append(f" */")
    lines.append(f"static const int16_t {var_name}[] = {{")

    for i in range(0, count, 16):
        chunk = samples[i:i + 16]
        lines.append("    " + ", ".join(f"0x{s & 0xFFFF:04X}" for s in chunk) + ",")

    lines.append("};")
    lines.append(f"#define {var_name.upper()}_COUNT  {count}")

    return "\n".join(lines)


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    out_path   = os.path.normpath(os.path.join(script_dir, "..", "main", "tts_data.h"))

    print("ESP32-P4 TTS audio generator  (engine: edge-tts / Microsoft Neural TTS)")
    print(f"Output: {out_path}")
    print()

    grant_c = phrase_to_c_array("Hoşgeldiniz", "tts_grant_samples")
    deny_c  = phrase_to_c_array("Kartınızı kontrol ediniz", "tts_deny_samples")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("#pragma once\n")
        f.write("/*\n")
        f.write(" * tts_data.h — Turkish TTS audio samples for ESP32-P4 speaker\n")
        f.write(" * Auto-generated by tools/gen_tts.py — DO NOT hand-edit.\n")
        f.write(" * Re-run gen_tts.py to regenerate after phrase changes.\n")
        f.write(" *\n")
        f.write(f" * Engine: edge-tts  Voice: {EDGE_TTS_VOICE}\n")
        f.write(" * Format: 16 kHz, 16-bit signed PCM, mono.\n")
        f.write(" * Played via play_pcm_mono() in audio.c (duplicated to stereo L+R).\n")
        f.write(" */\n")
        f.write("#include <stdint.h>\n\n")
        f.write(grant_c)
        f.write("\n\n")
        f.write(deny_c)
        f.write("\n")

    print()
    print(f"Done. Generated {out_path}")
    print("Now run: idf.py build")


if __name__ == "__main__":
    main()
